<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [30]:
#Notes for efficienccy:
#shift + tab when cursor is in arguments to bring up its documentation
#ex: pd.DataFrame(Shift+tab here)
#recall: Json == Dictionary
#to know functions of pandas:
dir(pd)

['BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_hashtable',
 '_is_numpy_dev',
 '_lib',
 '_libs',
 '_np_version_under1p18',
 '_testing',
 '_tslib',
 '_typing',
 '_version',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

In [2]:
# Setup matplotlib to plot inline (within the notebook)
%matplotlib inline
# Import the pyplot module of Matplotlib as plt
import matplotlib.pyplot as plt
# Import pandas under the abbreviation 'pd'
import pandas as pd
# Import NumPy under the abbreviation 'np'
import numpy as np

In [102]:
# Import the heart disease dataset and save it to a variable
# using pandas and read_csv()
# Alternatively: You can directly pass the URL of a csv to read_csv()
acquis = pd.read_csv("datasets/startups/acquisitions.csv")
additions = pd.read_csv("datasets/startups/additions.csv")
companies = pd.read_csv("datasets/startups/companies.csv")
invests = pd.read_csv("datasets/startups/investments.csv")
rounds = pd.read_csv("datasets/startups/rounds.csv")
dfAll = [acquis, additions, companies, invests, rounds]

In [103]:
#shapes (rows x cols) of each dataset
for ele in dfAll:
    print(ele.shape)

(18969, 18)
(2213, 4)
(66368, 14)
(168647, 18)
(114949, 12)

In [101]:
import pandas as pd
def dfsCols(pad, csvNames, *args):
    """
    Takes dataframes and returns a dataframe (df) with each column having a df's
    column names. The "pad" is to make sure all lists of columns have 
    the same length padded out with "pad"
    Example
    pad = "XX", csvNames = ["cars", "planes"]
    args = [carsDF, planesDF]
    returned data frame:
            cars            planes
    0       numOfWheels     numOfWings
    1       manufacturer    manufacturer
    2       make            XX
    """
    cols = []
    maxArrayLen = 0
    for i, ele in enumerate(args):
        cols.append(ele.columns.tolist())
        maxArrayLen = max(maxArrayLen, len(cols[i]))
    
    dictCsvs = {}
    for i, ele in enumerate(args):
        cols[i] += [pad] * (maxArrayLen - len(cols[i])) #padding the lists to make them have equal lengths 
        dictCsvs.update({csvNames[i] : cols[i]})

    return pd.DataFrame(dictCsvs)

In [100]:
lstCsvNames = ["acquisitions", "additions", "companies", "investments", "rounds"]

dfAllCols = pd.DataFrame(dfsCols("", lstCsvNames, *dfAll))
dfAllCols

,acquisitions,additions,companies,investments,rounds
0,company_permalink,content,permalink,company_permalink,company_permalink
1,company_name,month_str,name,company_name,company_name
2,company_category_list,year_str,homepage_url,company_category_list,company_category_list
3,company_country_code,value,category_list,company_country_code,company_country_code
4,company_state_code,,funding_total_usd,company_state_code,company_state_code
5,company_region,,status,company_region,company_region
6,company_city,,country_code,company_city,company_city
7,acquirer_permalink,,state_code,investor_permalink,funding_round_permalink
8,acquirer_name,,region,investor_name,funding_round_type
9,acquirer_category_list,,city,investor_country_code,funding_round_code
10,acquirer_country_code,,funding_rounds,investor_state_code,funded_at
11,acquirer_state_code,,founded_at,investor_region,raised_amount_usd
12,acquirer_region,,first_funding_at,investor_city,
13,acquirer_city,,last_funding_at,funding_round_permalink,
14,acquired_at,,,funding_round_type,
15,acquired_month,,,funding_round_code,
16,price_amount,,,funded_at,
17,price_currency_code,,,raised_amount_usd,

In [111]:
acquis.sample(5).transpose()

,18952,9560,18148,11759,1492
company_permalink,/organization/zvrs,/organization/lincoln-snacks,/organization/viztu-technologies,/organization/numbercop,/organization/asic-architect
company_name,ZVRS,Lincoln Snacks,Viztu Technologies,NumberCop,ASIC Architect
company_category_list,NaN,Specialty Foods,3D|Software,Android|Cyber Security|iPhone|Mobile|Security|...,Semiconductors
company_country_code,USA,USA,USA,USA,USA
company_state_code,FL,NE,MA,CA,CA
company_region,Tampa,Omaha,Boston,SF Bay Area,SF Bay Area
company_city,Clearwater,Lincoln,Cambridge,San Francisco,Santa Clara
acquirer_permalink,/organization/kinderhook-industries-2,/organization/willis-stein-partnes,/organization/3d-systems,/organization/whitepages-com,/organization/snowbush
acquirer_name,Kinderhook Industries,Willis Stein & Partnes,3D Systems,Whitepages,Snowbush
acquirer_category_list,NaN,Business Services|Consumers,Software,Curated Web|Fraud Detection|Identity Managemen...,Semiconductors
acquirer_country_code,USA,USA,USA,USA,CAN
acquirer_state_code,NY,IL,SC,WA,ON
acquirer_region,New York City,Chicago,SC - Other,Seattle,Toronto
acquirer_city,New York,Chicago,Rock Hill,Seattle,Toronto
acquired_at,2/9/2015,3/2/2004,7/23/2012,6/10/2015,7/28/2008
acquired_month,2015-02,2004-03,2012-07,2015-06,2008-07
price_amount,NaN,NaN,NaN,NaN,1500000.0
price_currency_code,USD,USD,USD,USD,USD

In [112]:
additions.sample(5).transpose()

,82,702,1800,1490,1578
content,Acquisitions,IPOs,Rounds: private_equity,Rounds: debt_financing,Rounds: grant
month_str,1998-01,2013-03,2012-03,2014-01,2010-07
year_str,1998,2013,2012,2014,2010
value,7,19,7,359,10

In [113]:
companies.sample(5).transpose()

,30132,36514,1799,43295,65401
permalink,/organization/kalyan-jewellers,/organization/mobilitec,/organization/affibody,/organization/philz-coffee,/organization/your-pet-chef
name,Kalyan Jewellers,Mobilitec,Affibody,Philz Coffee,Your Pet Chef
homepage_url,http://www.kalyanjewellers.net/,NaN,http://www.affibody.com,http://philzcoffee.com,http://www.yourpetchef.com
category_list,Jewelry,Software,Biotechnology|Health Diagnostics,Coffee|E-Commerce,Pets
funding_total_usd,200000000,12100000,28499283,30000000,-
status,operating,operating,operating,operating,operating
country_code,IND,USA,SWE,USA,USA
state_code,NaN,CA,26,CA,IL
region,NaN,SF Bay Area,Stockholm,SF Bay Area,Chicago
city,NaN,San Mateo,Stockholm,San Francisco,Chicago
funding_rounds,1,1,1,2,1
founded_at,1/1/1993,1/1/2000,NaN,1/1/2003,5/1/2012
first_funding_at,8/26/2014,2/7/2005,3/30/2007,5/2/2013,10/27/2014
last_funding_at,8/26/2014,2/7/2005,3/30/2007,2/18/2015,10/27/2014

In [114]:
invests.sample(5).transpose()

,116307,93248,66722,15087,64982
company_permalink,/organization/pubmatic,/organization/moseeker,/organization/hyper9,/organization/b2x-care-solutions,/organization/hipcricket
company_name,PubMatic,MoSeeker,Hyper9,B2X Care Solutions,Hipcricket
company_category_list,Advertising|Marketing Automation,Media|Recruiting|Social Media,Software,Customer Service|Hardware + Software|Mobile|Su...,Advertising|Business Analytics|Mobile Commerce
company_country_code,USA,CHN,USA,DEU,USA
company_state_code,CA,23,TX,2,NY
company_region,SF Bay Area,NaN,Austin,Munich,New York City
company_city,Redwood City,NaN,Austin,Munich,New York
investor_permalink,/organization/nexus-venture-partners,/person/zhu-li,/organization/venrock,/organization/grazia-equity,/organization/broadmark-capital
investor_name,Nexus Venture Partners,Zhu Li,Venrock,Grazia Equity,Broadmark Capital
investor_country_code,USA,NaN,USA,DEU,USA
investor_state_code,CA,NaN,CA,1,WA
investor_region,SF Bay Area,NaN,SF Bay Area,Stuttgart,Seattle
investor_city,Menlo Park,NaN,Palo Alto,Stuttgart,Seattle
funding_round_permalink,/funding-round/35353560b0df2f73dc404e5d2d27844e,/funding-round/203442569c8c11a5c1e27dfe228996bf,/funding-round/eab573901af0644813963088ab00241c,/funding-round/83f2d9e955efdd370a22eccc6765b5d4,/funding-round/b07a0ba3dfba0f273445d722fe5b33ee
funding_round_type,venture,angel,venture,private_equity,venture
funding_round_code,D,NaN,B,NaN,A
funded_at,6/6/2012,9/30/2014,2/26/2009,1/1/2012,3/22/2007
raised_amount_usd,32000000.0,814196.0,8000000.0,NaN,2000000.0

In [115]:
rounds.sample(5).transpose()

,90033,47532,79800,43219,4401
company_permalink,/organization/singld-out,/organization/influicity,/organization/pyxis-technology,/organization/hdl-therapeutics,/organization/align-3
company_name,Singld Out,Influicity,Pyxis Technology,hdl therapeutics,Align
company_category_list,Online Dating|Professional Networking|Social N...,Celebrity|Enterprise Software|Marketplaces|Med...,Software,Biotechnology,Lifestyle|Online Dating|Social Network Media|S...
company_country_code,USA,CAN,USA,USA,USA
company_state_code,CA,ON,TX,NJ,CA
company_region,San Diego,Toronto,Austin,Newark,Los Angeles
company_city,San Diego,Toronto,Austin,Short Hills,Los Angeles
funding_round_permalink,/funding-round/fd82616a890814bcc867a01918e90f17,/funding-round/16be95b50f427693f955e1d8a3974439,/funding-round/a5fc767ec9bafa9bd9fb93788f56e6a7,/funding-round/3e460679694b64b5b8624c86f0700661,/funding-round/1fddfe150e3c4c99986266a8af4d0ecc
funding_round_type,seed,seed,venture,venture,seed
funding_round_code,NaN,NaN,NaN,B,NaN
funded_at,10/28/2014,3/2/2015,4/20/2010,12/31/2014,9/1/2014
raised_amount_usd,600000.0,NaN,1270000.0,2045000.0,100000.0

Seeing (via a dataframe) the columns in the dataframes

In [69]:
#getting all (unique) columns of the datasets
uniqueCols = set() #or: instead of "{}", "set()"
for ele in dfAll:
    cols = ele.columns.tolist() #".tolist()" to make it a list (side note: ".values" to make it a numpy.ndarray)
    
    uniqueCols.update(cols) #use ".add()" for elements, ".update()" for lists

In [93]:
#sorting the columns alphabetically
tempList = list(uniqueCols)
tempList.sort()
uniqueCols = tempList
uniqueCols

['acquired_at',
 'acquired_month',
 'acquirer_category_list',
 'acquirer_city',
 'acquirer_country_code',
 'acquirer_name',
 'acquirer_permalink',
 'acquirer_region',
 'acquirer_state_code',
 'category_list',
 'city',
 'company_category_list',
 'company_city',
 'company_country_code',
 'company_name',
 'company_permalink',
 'company_region',
 'company_state_code',
 'content',
 'country_code',
 'first_funding_at',
 'founded_at',
 'funded_at',
 'funding_round_code',
 'funding_round_permalink',
 'funding_round_type',
 'funding_rounds',
 'funding_total_usd',
 'homepage_url',
 'investor_city',
 'investor_country_code',
 'investor_name',
 'investor_permalink',
 'investor_region',
 'investor_state_code',
 'last_funding_at',
 'month_str',
 'name',
 'permalink',
 'price_amount',
 'price_currency_code',
 'raised_amount_usd',
 'region',
 'state_code',
 'status',
 'value',
 'year_str']

Seeing the columns in a dataframe

In [3]:
# Check the first 5 rows of the data
acquis.head()

,company_permalink,company_name,company_category_list,company_country_code,company_state_code,company_region,company_city,acquirer_permalink,acquirer_name,acquirer_category_list,acquirer_country_code,acquirer_state_code,acquirer_region,acquirer_city,acquired_at,acquired_month,price_amount,price_currency_code
0,/organization/003-ru,003.RU,Consumer Electronics|Electronics|Internet,RUS,48,Moscow,Moscow,/organization/media-saturn,Media Saturn,Enterprise Software|Media|Sales and Marketing,ESP,56,Barcelona,Barcelona,2012-07-23,2012-07,NaN,USD
1,/organization/0958572-b-c-ltd,0958572 B.C. Ltd.,NaN,NaN,NaN,NaN,NaN,/organization/atlas-intellectual-property-mana...,ATLAS Intellectual Property Management Co.,Finance|FinTech|Mobile|Telecommunications,USA,WA,Seattle,Seattle,2012-02-02,2012-02,9000000.0,USD
2,/organization/1-800-communications,1-800 Communications,NaN,USA,NY,Long Island,Hicksville,/organization/carsdirect-com,CarsDirect.com,E-Commerce,USA,CA,Los Angeles,El Segundo,2005-06-12,2005-06,NaN,USD
3,/organization/1-800-contacts,1-800 Contacts,Consumer Goods|Retail,USA,UT,Salt Lake City,Draper,/organization/thomas-h-lee-partners,Thomas H. Lee Partners,Business Development|Impact Investing|Investme...,USA,MA,Boston,Boston,2014-01-07,2014-01,NaN,USD
4,/organization/1-844-446-4460-pogo-customer-ser...,Games Support +1-800-311-5934 Pogo Games techn...,NaN,NaN,NaN,NaN,NaN,/organization/pogo-customer-service-number-1-8...,Games Support +1-800-311-5934 Pogo Games techn...,NaN,USA,NY,New York City,Mamaroneck,2001-02-02,2001-02,NaN,USD